name: ProyectEXTINCTION
version: 1.0
main: com.proyectoextinction.Main
api-version: 1.20
commands:
  extinctionmenu:
    description: Abre el inventario creativo de ProyectEXTINCTION
    aliases: [pext, extinction]
